### ISSUE TITLE
can u provide some image/video preview?

### ISSUE THREAD

**Issue by fukemy** [Gustash/react-native-chat-bubbles#1]
Hi, thanks for work on chathead, I am finding some solutions for android chathead like Messenger app, can u take some screenshot? Thanks so much

**Comment by Gustash** [comment]
This project was started mostly for experimentation. I never got close to a finished implementation, and I never will as I don't have interest in this particular feature, as well as React Native in general these days. 

I'd suggest you look for another project, or request to assume control of this repo in case you want to continue an implementation.

**Comment by fukemy** [comment]
ok thanks
